image: ghcr.io/galoisinc/cryptol:2.11.0

tasks:
  - init: gp preview README.md
    command: echo 'Welcome to the Cryptol course!'

vscode:
  extensions:
    # Add PDF viewing support to VSCode
    - https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
    # Enhanced Markdown support (displays equations in markdown)
    # - shd101wyy.markdown-preview-enhanced

