theme: jekyll-theme-cayman
# remote_theme: user/name
baseurl: /cryptol-course
plugins:
  - jekyll-relative-links
include:
  - labs/KeyWrapping/kwtestvectors/KW_AD_128_inv.txt
  - labs/KeyWrapping/kwtestvectors/KW_AD_128.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AE_128_inv.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AE_192.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AD_192.txt
  - labs/KeyWrapping/kwtestvectors/KW_AD_256_inv.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AE_256_inv.txt
  - labs/KeyWrapping/kwtestvectors/KW_AE_128.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AE_192_inv.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AD_256.txt
  - labs/KeyWrapping/kwtestvectors/TKW_AE_inv.txt
  - labs/KeyWrapping/kwtestvectors/KW_AD_192_inv.txt
  - labs/KeyWrapping/kwtestvectors/TKW_AD_inv.txt
  - labs/KeyWrapping/kwtestvectors/TKW_AE.txt
  - labs/KeyWrapping/kwtestvectors/TKW_AD.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AE_256.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AD_128.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AD_256_inv.txt
  - labs/KeyWrapping/kwtestvectors/KW_AE_256_inv.txt
  - labs/KeyWrapping/kwtestvectors/KW_AE_192.txt
  - labs/KeyWrapping/kwtestvectors/KW_AD_192.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AD_128_inv.txt
  - labs/KeyWrapping/kwtestvectors/KW_AE_128_inv.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AE_128.txt
  - labs/KeyWrapping/kwtestvectors/Readme.txt
  - labs/KeyWrapping/kwtestvectors/KW_AD_256.txt
  - labs/KeyWrapping/kwtestvectors/KW_AE_192_inv.txt
  - labs/KeyWrapping/kwtestvectors/KW_AE_256.txt
  - labs/KeyWrapping/kwtestvectors/KWP_AD_192_inv.txt
  - labs/KeyWrapping/spec/DES/Cipher.cry
  - labs/KeyWrapping/spec/DES/DES.cry
  - labs/KeyWrapping/spec/DES/TripleDES.cry
  - labs/KeyWrapping/spec/NIST_800_38F/W64.cry
  - labs/KeyWrapping/spec/NIST_800_38F/TKW.cry
  - labs/KeyWrapping/spec/NIST_800_38F/TDEA.cry
  - labs/KeyWrapping/spec/NIST_800_38F/AES128.cry
  - labs/KeyWrapping/spec/NIST_800_38F/KW.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/all_tests.icry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KWP_AD_AES192.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KW_AE_AES256.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KWP_AE_AES128.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KWP_AD_AES256.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KW_AD_AES128.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KW_AE_AES192.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AD_128_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AD_128.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AE_128_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AE_192.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AD_192.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AD_256_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AE_256_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AE_128.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AE_192_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AD_256.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AD_192_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AE_256.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AD_128.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AD_256_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AE_256_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AE_192.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AD_192.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AD_128_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AE_128_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AE_128.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/Readme.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AD_256.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AE_192_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KW_AE_256.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/vectors/KWP_AD_192_inv.txt
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KWP_AE_AES192.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KW_AD_AES256.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KWP_AD_AES128.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KWP_AE_AES256.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KW_AE_AES128.cry
  - labs/KeyWrapping/spec/NIST_800_38F/tests/Test_KW_AD_AES192.cry
  - labs/KeyWrapping/spec/NIST_800_38F/docs/NIST.SP.800-38F.pdf
  - labs/KeyWrapping/spec/NIST_800_38F/W32.cry
  - labs/KeyWrapping/spec/NIST_800_38F/AES256.cry
  - labs/KeyWrapping/spec/NIST_800_38F/KWP.cry
  - labs/KeyWrapping/spec/NIST_800_38F/AES192.cry
  - labs/KeyWrapping/spec/NIST_800_38F/W.cry
  - labs/KeyWrapping/spec/AES/AES128.cry
  - labs/KeyWrapping/spec/AES/AES256.cry
  - labs/KeyWrapping/spec/AES/AES192.cry
