theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - labs/Interpreter/Interpreter.md
  - labs/KeyWrapping/KeyWrapping.md
  - labs/KeyWrapping/KeyWrappingAnswers.md
  - labs/SimonSpeck/SimonSpeck.md
  - labs/SimonSpeck/Speck/README.md
  - labs/CryptoProofs/CryptoProofsAnswers.md
  - labs/CryptoProofs/CryptoProofs.md
  - labs/CRC/CRCAnswers.md
  - labs/CRC/CRC.md
  - labs/ProjectEuler/ProjectEulerAnswers.md
  - labs/ProjectEuler/ProjectEuler.md
  - labs/Language/Basics.md
  - labs/Salsa20/Salsa20Answers.md
  - labs/Salsa20/Salsa20Props.md
  - labs/Salsa20/Salsa20.md
  - labs/Salsa20/Salsa20PropsAnswers.md
  - labs/LoremIpsum/LoremIpsumAnswers.md
  - labs/LoremIpsum/LoremIpsum.md
  - labs/Transposition/CommonProperties.md
  - labs/Transposition/TranspositionAnswers.md
  - labs/Transposition/Transposition.md
  - labs/Transposition/EsreverAnswers.md
  - labs/Transposition/RailFence.md
  - labs/Transposition/RailFenceAnswers.md
  - labs/Transposition/Contents.md
  - labs/Transposition/Scytale.md
  - labs/Transposition/Esrever.md
  - labs/Transposition/CommonPropertiesAnswers.md
  - labs/Transposition/ScytaleAnswers.md
  - labs/Transposition/Route.md
  - labs/Overview/Overview.md
  - labs/Demos/SAW/ArithmeticVerifications/ArithmeticVerifications.md
  - labs/Demos/SAW/Demos.md
  - labs/Demos/SAW/Bittwiddling/Bittwiddling.md
  - labs/Demos/SAW/Bittwiddling/BittwiddlingAnswers.md
  - labs/Demos/Cryptol/Caesar.md
  - labs/Demos/Cryptol/Sudoku.md
  - labs/Demos/Cryptol/Demos.md
  - labs/Demos/Cryptol/NQueens.md
  - labs/Demos/Cryptol/OneTimePad.md
  - INSTALL.md
  - README.md
  - cryptol-style.md
