name: Cryptol Checks

on: [push]

jobs:
  ci-load:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/weaversa/cryptol-course:2.12
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Start cryptol-remote-api server
      - run: start-cryptol-remote-api.sh
      # Load all files
      - run: python3 .ci/ci_load.py

  ci-check:
    needs: ci-load
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/weaversa/cryptol-course:2.12
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set pythonpath
        run: echo "PYTHONPATH=${PYTHONPATH}:${PWD}/.ci" >> $GITHUB_ENV
      # Start cryptol-remote-api server
      - run: start-cryptol-remote-api.sh
      # Run checks
      - run: for f in `find . -name "ci.py"`; do python3 $f; done
