name: Cryptol Loads

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/weaversa/cryptol-course:2.12
    steps:
     - name: Checkout
       uses: actions/checkout@v3
# README tests
     - run: cryptol -e -c ":m README" -c ":prove"
# Interpreter lab tests
     - run: cryptol -e -c ":m labs::Interpreter::Interpreter" -c ":s base=10" -c "x + 2"
#    - run: cryptol -e -b labs/Interpreter/test.sry
# Arithmetic verification tests
     - run: make -C labs/Demos/SAW/ArithmeticVerifications
# Bittwiddling lab tests
     - run: cryptol -e -c ":m labs::Demos::SAW::Bittwiddling::Bittwiddling"
     - run: clang -emit-llvm -c labs/Demos/SAW/Bittwiddling/bittwiddling.c -o labs/Demos/SAW/Bittwiddling/bittwiddling.bc
     - run: cryptol -e -c ":m labs::Demos::SAW::Bittwiddling::BittwiddlingAnswers"
     - run: cd labs/Demos/SAW/Bittwiddling && saw BittwiddlingAnswers.saw
# Salsa20 lab tests
     - run: cryptol -e -c ":m labs::Salsa20::Salsa20"
     - run: cryptol -e -c ":m labs::Salsa20::Salsa20Answers"
     - run: cryptol -e -c ":m labs::Salsa20::Salsa20Props"
     - run: cryptol -e -c ":m labs::Salsa20::Salsa20PropsAnswers"
     - run: cryptol -e -c ":m labs::Salsa20::spec::Salsa20"
# CRC lab tests
     - run: cryptol -e -c ":m labs::CRC::CRC"
     - run: cryptol -e -c ":m labs::CRC::CRCAnswers"
     - run: cryptol -e -c ":m labs::CRC::spec::CRC"
# LoremIpsum tests
     - run: cryptol -e -c ":m labs::LoremIpsum::LoremIpsum"
     - run: cryptol -e -c ":m labs::LoremIpsum::LoremIpsumAnswers"
     - run: cryptol -e -c ":m labs::LoremIpsum::KLI20"
# Cryptol demo lab tests
     - run: cryptol -e -c ":m labs::Demos::Cryptol::Caesar"
     - run: cryptol -e -c ":m labs::Demos::Cryptol::OneTimePad"
     - run: cryptol -e -c ":m labs::Demos::Cryptol::NQueens"
     - run: cryptol -e -c ":m labs::Demos::Cryptol::Sudoku"
# Overview lab tests
     - run: cryptol -e -c ":m labs::Overview::Overview"
# Language Basics lab tests
     - run: cryptol -e -c ":m labs::Language::Basics"
     - run: cryptol -e -c ":m labs::Language::IntroTypeHackery"
# Project Euler lab tests
     - run: cryptol -e -c ":m labs::ProjectEuler::ProjectEuler"
     - run: cryptol -e -c ":m labs::ProjectEuler::ProjectEulerAnswers"
     - run: cryptol -e -c ":m labs::ProjectEuler::keylog"
     - run: cryptol -e -c ":m labs::ProjectEuler::cipher1"
     - run: cryptol -e -c ":m labs::ProjectEuler::cipher2"
# Crypto Proofs lab tests
     - run: cryptol -e -c ":m labs::CryptoProofs::CryptoProofs"
     - run: cryptol -e -c ":m labs::CryptoProofs::CryptoProofsAnswers"
# Key Wrapping lab tests
     - run: cryptol -e -c ":m labs::KeyWrapping::KeyWrapping"
     - run: cryptol -e -c ":m labs::KeyWrapping::KeyWrappingAnswers"
# Simon and Speck lab tests
     - run: cryptol -e -c ":m labs::SimonSpeck::SimonSpeck"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_64_96"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_128_256"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_32_64"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_48_96"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_128_192"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_96_96"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_48_72"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::Simon"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_128_128"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_64_128"
     - run: cryptol -e -c ":m labs::SimonSpeck::Simon::simon_96_144"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_128_192"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_128_256"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_96_96"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_48_72"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_128_128"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_32_64"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_48_96"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::Speck"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_64_96"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_96_144"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::speck_64_128"
     - run: cryptol -e -c ":m labs::SimonSpeck::SpeckAnswers::SpeckTestVectors"
# Transpostion Lab Tests
     - run: cryptol -e -c ":m labs::Transposition::CommonProperties"
     - run: cryptol -e -c ":m labs::Transposition::CommonPropertiesAnswers"
     - run: cryptol -e -c ":m labs::Transposition::Transposition"
     - run: cryptol -e -c ":m labs::Transposition::TranspositionAnswers"
     - run: cryptol -e -c ":m labs::Transposition::Esrever"
     - run: cryptol -e -c ":m labs::Transposition::EsreverAnswers"
     - run: cryptol -e -c ":m labs::Transposition::Scytale"
     - run: cryptol -e -c ":m labs::Transposition::ScytaleAnswers"
     - run: cryptol -e -c ":m labs::Transposition::RailFence"
     - run: cryptol -e -c ":m labs::Transposition::RailFenceAnswers"
     - run: cryptol -e -c ":m labs::Transposition::Route"
